name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install MinGW
      uses: egor-tensin/setup-mingw@v2
      
    - name: Install the Windows/MinGW Target for rust
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: stable-x86_64-unknown-linux-gnu
        targets: x86_64-unknown-linux-gnu, x86_64-pc-windows-gnu
        
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.2.1
      
    - name: Build x86_64-unknown-linux-gnu
      run: cargo build --verbose --release --target "x86_64-unknown-linux-gnu"
      
    - name: Upload the x86_64-unknown-linux-gnu build as an artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: x86_64-unknown-linux-gnu
        path: target/x86_64-unknown-linux-gnu/release/icy-sysmonitor
        
    - name: Build x86_64-pc-windows-gnu
      run: cargo build --verbose --release --target "x86_64-pc-windows-gnu"
    
    - name: Upload the x86_64-pc-windows-gnu build as an artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: x86_64-pc-windows-gnu
        path: target/x86_64-pc-windows-gnu/release/icy-sysmonitor
      
    - name: Run tests
      run: cargo test --verbose
      
    
      
